### ISSUE TITLE
Crash on entering network mode. build |2018.26450

### ISSUE THREAD

**Issue by barakooda** [landonth/normals-gpu#2]
great work but,
Crash on entering network mode.

**Comment by barakooda** [comment]
My mistake, 
Its takes about 20 seconds to enter the network mode.

**Comment by loopervfx** [comment]
I baked out some of the SOPs into .tog files that were cooking all at once on entering network editor depending on the options you chose in the perform UI to cook each SOP chain on demand. So this should be a bit be faster now than it was. But it will vary depending on your hardware.
