### ISSUE TITLE
replace texelFetchBuffer() for compatibility

### ISSUE THREAD

**Issue by brvoigt** [landonth/normals-gpu#3]
texelFetchBuffer() will only compile on nvidia drivers. Recommend changing all texelFetchBuffer with newer texelFetch for better compatibility.

There are 5 instances of it in phong_normals_Geo.glsl

**Comment by loopervfx** [comment]
Done. Thanks for the heads up on that, Ben!

**Comment by brvoigt** [comment]
Thanks, confirmed working great!
